export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://hemguiden.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/robotdammsugare","priority":"0.8","changefreq":"weekly"},{"path":"/kaffemaskin","priority":"0.8","changefreq":"weekly"},{"path":"/luftrenare","priority":"0.8","changefreq":"weekly"},{"path":"/airfryer","priority":"0.8","changefreq":"weekly"},{"path":"/smarta-hem","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/de-longhi-primadonna-soul-vs-philips-5400-series-lattego","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/de-longhi-primadonna-soul-vs-jura-e8","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/de-longhi-primadonna-soul-vs-nespresso-lattissima-pro","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/de-longhi-primadonna-soul-vs-siemens-eq-500","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/de-longhi-primadonna-soul-vs-melitta-caffeo-barista-ts-smart","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/de-longhi-primadonna-soul-vs-krups-evidence-plus","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/philips-5400-series-lattego-vs-jura-e8","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/philips-5400-series-lattego-vs-nespresso-lattissima-pro","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/philips-5400-series-lattego-vs-siemens-eq-500","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/philips-5400-series-lattego-vs-melitta-caffeo-barista-ts-smart","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/philips-5400-series-lattego-vs-krups-evidence-plus","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jura-e8-vs-nespresso-lattissima-pro","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jura-e8-vs-siemens-eq-500","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jura-e8-vs-melitta-caffeo-barista-ts-smart","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jura-e8-vs-krups-evidence-plus","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nespresso-lattissima-pro-vs-siemens-eq-500","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nespresso-lattissima-pro-vs-melitta-caffeo-barista-ts-smart","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nespresso-lattissima-pro-vs-krups-evidence-plus","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/siemens-eq-500-vs-melitta-caffeo-barista-ts-smart","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/siemens-eq-500-vs-krups-evidence-plus","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/melitta-caffeo-barista-ts-smart-vs-krups-evidence-plus","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-24</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }